#
# group_by: ['ok','atencao', 'gravissimo']

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf-rules
  labels:
    name: prometheus-server-conf-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
      - name:  Low container memory usage
        rules:
        - alert: High Pod Memory
          expr: sum(container_memory_usage_bytes) < 1
          for: 1m
          labels:
            severity: OK
          annotations:
            summary: High Memory Usage
      
      - name: Normal container memory usage
        rules:
        - alert: High Pod Memory
          expr: sum(container_memory_usage_bytes) > 200
          for: 1m
          labels:
            severity: ATENCAO
          annotations:
            summary: Este é um alerta do alto consumo de memoria.
       
      - name: High container memory usage
        rules:
        - alert: High Container Memory
          expr: sum(container_memory_usage_bytes) > 50000000000
          for: 1m
          labels:
            severity: CRITICO
          annotations:
            summary: Este é um alerta do alto consumo de memoria, NIVEL CRITICO.
      
  