kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'localhost:25'
      smtp_from: YOUR EMAIL

    templates:
      - '/etc/alertmanager-templates/*.tmpl'

    route:
      group_by: ['OK','ATENCAO', 'CRITICO']
      group_wait: 30s
      group_interval: 30m
      repeat_interval: 1h
      receiver: 'email'

    receivers:
    - name: 'email'
      email_configs:
      - to: YOUR EMAIL
        from: YOUR EMAIL
        smarthost: smtp.gmail.com:587
        auth_username: YOUR EMAIL
        auth_identity: YOUR EMAIL
        auth_password: 'YOUR  EMAIL PASSWORD TO EFS'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']